### ISSUE TITLE
Can't spin up pact_broker-docker:latest, 2.7.0.beta.2-1, or 2.7.0.beta.3-1

### ISSUE THREAD

**Issue by mattermack** [DiUS/pact_broker-docker#53] opened 2017-11-02 19:25 UTC
Following https://github.com/DiUS/pact_broker-docker/issues/46, I got a fresh docker install of 2.4.0-2.

For latest, 2.7.0.beta.2-1, or 2.7.0.beta.3-1, I repeatedly ran into ...

Could not spawn process for application /home/app/pact_broker: An error occured while starting up the preloader.
`Error ID: 66ef0932
  Error details saved to: /tmp/passenger-error-xHOaHz.html
  Message from application: uninitialized constant PactBroker::Api::Resources::BaseResource (NameError)`

In 2.7.0.beta.3-1, I also got 
`App 45 stderr: Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
App 45 stderr:     https://github.com/rvm/rvm/issues/3212`

To replicate this:
1.  Spin up an entirely new environment (in my case a basic Amazon Linux AMI 2017.09.0 (HVM), SSD Volume Type )
2. Follow  [POSTGRESQL.md](https://github.com/DiUS/pact_broker-docker/blob/master/POSTGRESQL.md) exactly up until the next step
3. Run `docker run --name pactbroker --link pactbroker-db:postgres -e PACT_BROKER_DATABASE_USERNAME=pactbrokeruser -e PACT_BROKER_DATABASE_PASSWORD=TheUserPassword -e PACT_BROKER_DATABASE_HOST=postgres -e PACT_BROKER_DATABASE_NAME=pactbroker -d -p 80:80 dius/pact-broker:2.7.0.beta.2-1`
4. Hit the url, see the error page
5. In the docker container, cat /var/log/nginx/error.log

Here is the full error log:
[error.log](https://github.com/DiUS/pact_broker-docker/files/1439077/error.log)

**Comment by mattermack** [comment] 2017-11-02 21:48
"Have a look at the releasing.md file, and try running the test script." ... going to try that.

**Comment by bethesque** [comment] 2017-11-02 22:25
Not sure why I'm not getting the error, but there is a missing require. I'll add it and do a new release.

**Comment by bethesque** [comment] 2017-11-02 22:56
I've just pushed 2.8.0.beta.4 (accidental minor version bump because I was too late on the ctl+c for the default release script and accidentally committed the change). Let me know how it goes. I'll be putting out a new version of the CL and broker in the next few days with some improvements. There will be breaking changes as the features are in beta, so just grab the latest versions of everything when you're testing.

**Comment by bethesque** [comment] 2017-11-02 23:01
FYI, currently, you have to say `can-i-deploy` and specify all the dependencies. I'm working on a `can-i-deploy` where you just give the one pacticipant/version and it works out the dependencies for you.

**Comment by nebez** [comment] 2018-06-26 15:03
Having the same issue with `latest`, `2.23.1-1`, and `2.23.2-1`

**Comment by nebez** [comment] 2018-06-26 15:07
Seems like adding this require:

```ruby
require 'pact_broker/api/resources/base_resource'
```
To this file in the docker image fixed it: `/home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.2/lib/pact_broker/api/resources/verification_triggered_webhooks.rb`

**Comment by bethesque** [comment] 2018-06-26 21:28
Thanks. I've released another fix! I can't work out why you get this error consistently, but I can't reproduce it. The only way this can happen is if the `verification_triggered_webhooks.rb` is the very first of the resource files to be loaded, and that's a 1 in 42 (0.02) chance!

**Closed** 2018-06-26 21:29 UTC
