### ISSUE TITLE
schema migration table missing in pact-broker:2.23.0-1

### ISSUE THREAD

**Issue by signed** [DiUS/pact_broker-docker#70] opened 2018-06-22 20:11 UTC
# Pre issue-raising checklist

I have already (please mark the applicable with an `x`):

* [x] Confirmed this is the right place to raise the issue - issues for the Pact Broker application itself should be raised in the [Pact Broker](https://github.com/pact-foundation/pact_broker) project.
* [x] Upgraded to the latest Pact Broker Docker image OR
* [x] Checked the [CHANGELOG](/CHANGELOG.md) to see if the issue I am about to raise has been fixed
* [x] Read the [Troubleshooting](https://github.com/DiUS/pact_broker-docker/wiki/Troubleshooting) page

## Software versions
* **pact-broker gem version:** eg 2.23.0
* **pact-broker docker version:** eg 2.23.0-1
* **OS**: Mac OSX 10.13.4

## Expected behaviour
The pact broker web page is displayed after starting the image

## Actual behaviour
When I open the the web ui I get ´We're sorry, but something went wrong´
## Steps to reproduce
Here is my [docker-compose.yml](https://github.com/signed/talk-contract-tests/blob/we-are-sorry/pact/broker/docker-compose.yml#L17).

Without any prior state I started the database with `docker-compose up postgres` and started the broker with `docker-compose up broker_app`.

## Relevent log files

```
broker_app_1  | App 49 stdout: 
broker_app_1  | App 49 stdout: E, [2018-06-22T19:54:45.786606 #49] ERROR -- : PG::UndefinedTable: ERROR:  relation "schema_migrations" does not exist
broker_app_1  | App 49 stdout: LINE 1: SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
broker_app_1  | App 49 stdout:                                   ^: SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1
broker_app_1  | App 49 stdout: E, [2018-06-22T19:54:45.810695 #49] ERROR -- : PG::UndefinedTable: ERROR:  relation "schema_info" does not exist
broker_app_1  | App 49 stdout: LINE 1: SELECT NULL AS "nil" FROM "schema_info" LIMIT 1
broker_app_1  | App 49 stdout:                                   ^: SELECT NULL AS "nil" FROM "schema_info" LIMIT 1
broker_app_1  | App 49 stderr: 
broker_app_1  | App 49 stderr: Warning: PATH set to RVM ruby but GEM_HOME and/or GEM_PATH not set, see:
broker_app_1  | App 49 stderr:     https://github.com/rvm/rvm/issues/3212
broker_app_1  | App 49 stderr: 
broker_app_1  | App 49 stdout: 
broker_app_1  | [ E 2018-06-22 19:54:48.8202 28/Te age/Cor/App/Implementation.cpp:304 ]: Could not spawn process for application /home/app/pact_broker: An error occurred while starting up the preloader.
broker_app_1  |   Error ID: 7834aac7
broker_app_1  |   Error details saved to: /tmp/passenger-error-73uuPC.html
broker_app_1  |   Message from application: uninitialized constant PactBroker::Api::Resources::BaseResource (NameError)
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources/pact_triggered_webhooks.rb:6:in `<module:Resources>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources/pact_triggered_webhooks.rb:5:in `<module:Api>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources/pact_triggered_webhooks.rb:4:in `<module:PactBroker>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources/pact_triggered_webhooks.rb:3:in `<top (required)>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources.rb:9:in `require'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources.rb:9:in `block in <top (required)>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources.rb:8:in `glob'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api/resources.rb:8:in `<top (required)>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api.rb:2:in `require'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/api.rb:2:in `<top (required)>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/app.rb:137:in `require'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/app.rb:137:in `build_api'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/app.rb:103:in `prepare_app'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/pact_broker-2.23.0/lib/pact_broker/app.rb:32:in `initialize'
broker_app_1  |   config.ru:12:in `new'
broker_app_1  |   config.ru:12:in `block in <main>'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `instance_eval'
broker_app_1  |   /home/app/pact_broker/vendor/bundle/ruby/2.4.0/gems/rack-2.0.5/lib/rack/builder.rb:55:in `initialize'
broker_app_1  |   config.ru:1:in `new'
broker_app_1  |   config.ru:1:in `<main>'
broker_app_1  |   /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `eval'
broker_app_1  |   /usr/share/passenger/helper-scripts/rack-preloader.rb:110:in `preload_app'
broker_app_1  |   /usr/share/passenger/helper-scripts/rack-preloader.rb:156:in `<module:App>'
broker_app_1  |   /usr/share/passenger/helper-scripts/rack-preloader.rb:30:in `<module:PhusionPassenger>'
broker_app_1  |   /usr/share/passenger/helper-scripts/rack-preloader.rb:29:in `<main>'
broker_app_1  | 
broker_app_1  | 
broker_app_1  | [ E 2018-06-22 19:54:48.8289 28/T7 age/Cor/Con/CheckoutSession.cpp:285 ]: [Client 1-1] Cannot checkout session because a spawning error occurred. The identifier of the error is 7834aac7. Please see earlier logs for details about the error.
```

**Comment by bethesque** [comment] 2018-06-22 22:14
The `LINE 1: SELECT NULL AS "nil" FROM "schema_migrations" LIMIT 1` is normal and expected. The database adapter just logs when a table is not found, and in a new database, the schema_migrations won't be found.

The real error is `uninitialized constant PactBroker::Api::Resources::BaseResource (NameError)` which I cannot reproduce for the life of me! But I know how to fix it, so I've just released `2.23.1-1`. Closing this issue now. Please reopen if you have further issues.

**Closed by bethesque** 2018-06-22 22:14 UTC

**Comment by signed** [comment] 2018-06-22 22:38
Its working fine now. Thank you for the quick fix.

**Comment by bethesque** [comment] 2018-06-27 23:48
As mentioned in related issue, this is fixed.
